#################################################
## Configuration file for PhyloProcessR
## Workflow X2: Per-sample capture efficiency assessment
## Designed for large datasets (>1 TB) that cannot be downloaded all at once.
## Downloads, cleans, and assesses each sample one at a time, then deletes
## reads before moving to the next sample.
#################################################

# Working directory
#########################
# *** Full paths should be used whenever possible
working.directory = "/Path/to/where/the/stuff/will/happen"

# Global settings
#########################
# Number of threads
threads = 16
# Amount of memory to allocate in GB
memory = 120
# Hide verbose output for each function
quiet = FALSE

# Read input settings
#########################
# TRUE  = download reads from Dropbox (requires dropbox settings below)
# FALSE = use a local directory of reads (set read.directory below)
use.dropbox = TRUE
# Path to a local directory of raw reads; used when use.dropbox = FALSE.
# Reads may be in per-sample sub-directories or flat with a shared filename prefix.
read.directory = "/Path/to/local/raw-reads"
# CSV with two columns: "File" (filename prefix) and "Sample" (desired sample name).
# Used for Dropbox download sample matching; set to NULL if use.dropbox = FALSE.
sample.file = "file_rename.csv"
# Expected read length in bp, used for MegaBasePairs calculation
read.length = 150
# Name of the folder for all processed reads (created in working.directory)
processed.reads = "processed-reads"

# Dropbox download settings (only needed when use.dropbox = TRUE)
#########################
# Token file previously generated by the rdrop2 package (see rdrop2 documentation)
dropbox.token = "/Local/Path/to/Token/token.RDS"
# The Dropbox directory containing all sample read folders
dropbox.directory = "/Dropbox/Path/to/Reads"

# Cleanup settings
#########################
# TRUE = delete raw downloaded reads after processing each sample (recommended for large datasets)
delete.raw.reads = TRUE
# TRUE = delete cleaned reads after capture assessment (recommended for large datasets)
delete.cleaned.reads = TRUE

# Capture assessment settings
#########################
# Full path to the target probe/marker FASTA used for sequence capture
target.fasta = "/Path/to/probe-set.fa"

# Program paths
#########################
# When installed via conda, only the path to the conda bin directory is needed
conda.env = "/Path/to/conda/env/bin"
fastp.path = conda.env
samtools.path = conda.env
bwa.path = conda.env
