#################################################
## Configuration file for PhyloProcessR
#################################################

#Directories and input files
#########################
# *** Full paths should be used whenever possible
#The main working directory
working.directory = "/Path/to/where/the/stuff/will/happen"
#The file for the contaminant genomes (Genome, Accession columns); use NULL if download.contaminant.genomes = F
contaminant.genome.list = "decontamination_database.csv"
#The name for the dataset
dataset.name = "Descriptive-Name"

# Global settings
#########################
# number of threads
threads = 16
# Amount of memory to allocate in GB
memory = 120
# TRUE to overwrite previous runs. FALSE the script will resume but will not delete anything.
overwrite = FALSE
# Hide verbose output for each function
quiet = FALSE

#Raw read locations
#########################
#The file rename (File, Sample columns) for organizing reads or dropbox download. NA if reads already organized
sample.file = "file_rename.csv"
#TRUE = to rename reads from a csv file above, first column is "File" and second is "Sample"
organize.reads = TRUE
#The input raw read directory
read.directory = "/Path/to/where/the/raw/reads/are"
#The name for the processed reads folder
processed.reads = "processed-reads"
# TRUE to save a summary csv file of the raw sequence data
summary.fastq = TRUE

# For downloading reads from dropbox
#########################
#TRUE to download files from personal dropbox folder using token and read path 
dropbox.download = FALSE
#the dropbox directory your files are all contained within if dropbox.download = TRUE
dropbox.directory = "/Dropbox/Path/to/Reads"
#token file previously generated by the rdrop2 package (see this package for help)
dropbox.token = "/Local/Path/to/Token"

#FASTP read cleaning
#########################
# = TRUE to run all processing steps at once (much faster). Overrides settings below.
# = FALSE to run the separate analyses with TRUE below
fastp.complete = TRUE
#TRUE = to run adaptor removal on reads
remove.adaptors = TRUE
#TRUE to remove exact PCR duplicates
remove.duplicate.reads = TRUE
#TRUE to correct errors using the other read pair
error.correction = TRUE

#Other read processing tasks
############################
#normalizes read depth to facilitate assembly
normalize.reads = TRUE
#Merge paired end reads, helps with assembly
merge.pe.reads = TRUE
# Trims low quality ends off of reads (not recommended, hurts assembly)
quality.trim.reads <- FALSE

#Decontamination settings
#########################
#Remove contamination
decontamination = TRUE
#Download contaminat genomes from genbank if TRUE
download.contaminant.genomes = TRUE
#A path can be set to a local set of contaminant genomes if downloading does not work; NULL if downloading
decontamination.path = NULL
#include the human genome? Unless human is study organism or UCEs in mammals are used
include.human = TRUE
#Include the univec contaminant database?
include.univec = TRUE
#The matching proportion of bases for a contaminant hit and removal
decontamination.match = 1.0

#Program paths
#########################
### *** When installing the pipeline requirements via anaconda, only the path is needed to the conda bin directory
### Otherwise, if installed other ways, modify any of these to their path if R is not detecting system paths
conda.env = "/Path/to/conda/env/bin"
fastp.path = conda.env
samtools.path = conda.env
bwa.path = conda.env
spades.path = conda.env
bbnorm.path = conda.env
blast.path = conda.env