#################################################
## Configuration file for PhyloProcessR
## Workflow X2: Per-sample capture efficiency assessment
## Designed for large datasets (>1 TB) that cannot be downloaded all at once.
## Downloads, cleans, and assesses each sample one at a time, then deletes
## reads before moving to the next sample.
#################################################

# Working directory
#########################
# *** Full paths should be used whenever possible
working.directory = "/Path/to/where/the/stuff/will/happen"

# Global settings
#########################
# Number of threads
threads = 16
# Amount of memory to allocate in GB
memory = 120
# Hide verbose output for each function
quiet = FALSE

# Read input settings
#########################
# Select the read source — set exactly one to TRUE (or both FALSE for local):
#   use.dropbox = TRUE  → download each sample one at a time from Dropbox
#   use.sra     = TRUE  → download each sample one at a time from NCBI SRA
#   both FALSE          → use a local directory of reads (set read.directory)
use.dropbox = FALSE
use.sra     = FALSE
# Path to a local directory of raw reads; used when both flags above are FALSE.
# Reads may be in per-sample sub-directories or flat with a shared filename prefix.
read.directory = "/Path/to/local/raw-reads"
# CSV with two columns: "File" (filename prefix) and "Sample" (desired sample name).
# Used for Dropbox sample matching only; not needed for SRA or local runs.
sample.file = "file_rename.csv"
# Expected read length in bp, used for MegaBasePairs calculation
read.length = 150
# Name of the folder for all processed reads (created in working.directory)
processed.reads = "processed-reads"

# Dropbox download settings (only needed when use.dropbox = TRUE)
#########################
# Token file previously generated by the rdrop2 package (see rdrop2 documentation)
dropbox.token = "/Local/Path/to/Token/token.RDS"
# The Dropbox directory containing all sample read folders
dropbox.directory = "/Dropbox/Path/to/Reads"

# SRA download settings (only needed when use.sra = TRUE)
#########################
# Path to the SraRunInfo CSV exported from the NCBI SRA Run Selector.
# Must contain at minimum a 'Run' column with SRR/ERR/DRR accession numbers.
sra.info.file = "SraRunInfo.csv"
# Column to use directly as sample names. NULL (default) auto-builds names
# as Genus_species_SampleName (or Genus_species_SRRaccession when SampleName
# is blank). Set to a quoted column name to override.
sra.sample.name.column = NULL
# Only download rows whose LibraryStrategy matches this value
# (e.g. "Targeted-Capture"). NULL downloads all rows.
sra.filter.strategy = NULL
# Number of retry attempts per file before skipping a sample.
sra.max.retries = 3
# Seconds to wait between retry attempts.
sra.retry.delay = 10

# Cleanup settings
#########################
# TRUE = delete raw downloaded reads after processing each sample (recommended for large datasets)
delete.raw.reads = TRUE
# TRUE = delete cleaned reads after capture assessment (recommended for large datasets)
delete.cleaned.reads = TRUE

# Capture assessment settings
#########################
# Full path to the target probe/marker FASTA used for sequence capture
target.fasta = "/Path/to/probe-set.fa"

# Barcode scan settings  (calls MItoTrawlR::barcodeSampleScan)
#########################
# TRUE = run barcode identification after cleaning reads (recommended)
# FALSE = skip barcode identification entirely
run.barcode.scan = TRUE
# Full path to a FASTA of barcode reference sequence(s) used to recruit reads
# (e.g. a 16S rRNA or COI representative for the target taxa)
barcode.fasta = "/Path/to/barcode-reference.fa"
# Full path to a FASTA of named barcode sequences for local BLAST identification.
# NULL (recommended) queries NCBI nt remotely — no local database needed,
# but requires an internet connection. Remote queries are slower; for large
# datasets set this to a curated local database to avoid NCBI rate limits.
barcode.database.fasta = NULL
# Minimum number of iterative assembly rounds before convergence is tested.
# 3 is appropriate for barcode regions (much shorter than a mitogenome).
barcode.min.iterations = 3
# Maximum number of iterative assembly rounds.
barcode.max.iterations = 10
# Starting BBMap minimum identity for read recruitment. Permissive on first pass
# (0.70) to cast a wide net; automatically tightened to 0.95 once contigs assemble.
barcode.min.ref.id = 0.70
# Fraction above reference length that triggers the max-length guard.
barcode.per.max.length = 0.50

# Program paths
#########################
# When installed via conda, only the path to the conda bin directory is needed
conda.env = "/Path/to/conda/env/bin"
fastp.path = conda.env
samtools.path = conda.env
bwa.path = conda.env
bbmap.path = conda.env
spades.path = conda.env
cap3.path = conda.env
blast.path = conda.env
